### ISSUE TITLE
Playing audio sometimes crashes - EXCEPTION CAUGHT BY SERVICES LIBRARY

### ISSUE THREAD

**Issue by michalsrutek** [bdlukaa/just_audio#13]
**Which API doesn't behave as documented, and how does it misbehave?**
play - stop - setAsset - play

**Minimal reproduction project**
The example

**To Reproduce (i.e. user steps, not code)**
1. Play audio
2. Skip to next track.

**Error messages**

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following PlatformException was thrown while de-activating platform stream on channel
com.ryanheise.just_audio.events.fb5e3488-e6f6-42dc-98c6-fb2b2d6a0b68:
PlatformException(error, No active stream to cancel, null, null)

When the exception was thrown, this was the stack:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:649:9)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Expected behavior**
No crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/35694712/204148038-789982b2-c35b-4cfc-8f6f-1714e3a4ca01.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 

**Smartphone (please complete the following information):**
Nope

**Flutter SDK version**
```
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.19045.2251], locale en-US)
```

**Additional context**
None

**Comment by bdlukaa** [comment]
Hello! Can you try the latest branch and see if the issue is fixed?

```yaml
dependencies:
  just_audio_windows:
    git:
      url: https://github.com/bdlukaa/just_audio_windows
```
